--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/libi18n
build-by-default: true
branches:
  - pm4
projects:
  libi18n:
    path: ""
    model: virion
    type: library
...
